# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hebbs._generated import hebbs_pb2 as hebbs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hebbs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════
    Services
    ═══════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
                '/hebbs.v1.MemoryService/Remember',
                request_serializer=hebbs__pb2.RememberRequest.SerializeToString,
                response_deserializer=hebbs__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/hebbs.v1.MemoryService/Get',
                request_serializer=hebbs__pb2.GetRequest.SerializeToString,
                response_deserializer=hebbs__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/hebbs.v1.MemoryService/Recall',
                request_serializer=hebbs__pb2.RecallRequest.SerializeToString,
                response_deserializer=hebbs__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Prime = channel.unary_unary(
                '/hebbs.v1.MemoryService/Prime',
                request_serializer=hebbs__pb2.PrimeRequest.SerializeToString,
                response_deserializer=hebbs__pb2.PrimeResponse.FromString,
                _registered_method=True)
        self.Revise = channel.unary_unary(
                '/hebbs.v1.MemoryService/Revise',
                request_serializer=hebbs__pb2.ReviseRequest.SerializeToString,
                response_deserializer=hebbs__pb2.ReviseResponse.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/hebbs.v1.MemoryService/Forget',
                request_serializer=hebbs__pb2.ForgetRequest.SerializeToString,
                response_deserializer=hebbs__pb2.ForgetResponse.FromString,
                _registered_method=True)
        self.SetPolicy = channel.unary_unary(
                '/hebbs.v1.MemoryService/SetPolicy',
                request_serializer=hebbs__pb2.SetPolicyRequest.SerializeToString,
                response_deserializer=hebbs__pb2.SetPolicyResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════
    Services
    ═══════════════════════════════════════════════════════════════════════

    """

    def Remember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=hebbs__pb2.RememberRequest.FromString,
                    response_serializer=hebbs__pb2.RememberResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=hebbs__pb2.GetRequest.FromString,
                    response_serializer=hebbs__pb2.GetResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=hebbs__pb2.RecallRequest.FromString,
                    response_serializer=hebbs__pb2.RecallResponse.SerializeToString,
            ),
            'Prime': grpc.unary_unary_rpc_method_handler(
                    servicer.Prime,
                    request_deserializer=hebbs__pb2.PrimeRequest.FromString,
                    response_serializer=hebbs__pb2.PrimeResponse.SerializeToString,
            ),
            'Revise': grpc.unary_unary_rpc_method_handler(
                    servicer.Revise,
                    request_deserializer=hebbs__pb2.ReviseRequest.FromString,
                    response_serializer=hebbs__pb2.ReviseResponse.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=hebbs__pb2.ForgetRequest.FromString,
                    response_serializer=hebbs__pb2.ForgetResponse.SerializeToString,
            ),
            'SetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolicy,
                    request_deserializer=hebbs__pb2.SetPolicyRequest.FromString,
                    response_serializer=hebbs__pb2.SetPolicyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hebbs.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hebbs.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """═══════════════════════════════════════════════════════════════════════
    Services
    ═══════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/Remember',
            hebbs__pb2.RememberRequest.SerializeToString,
            hebbs__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/Get',
            hebbs__pb2.GetRequest.SerializeToString,
            hebbs__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/Recall',
            hebbs__pb2.RecallRequest.SerializeToString,
            hebbs__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/Prime',
            hebbs__pb2.PrimeRequest.SerializeToString,
            hebbs__pb2.PrimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/Revise',
            hebbs__pb2.ReviseRequest.SerializeToString,
            hebbs__pb2.ReviseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/Forget',
            hebbs__pb2.ForgetRequest.SerializeToString,
            hebbs__pb2.ForgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.MemoryService/SetPolicy',
            hebbs__pb2.SetPolicyRequest.SerializeToString,
            hebbs__pb2.SetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SubscribeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/hebbs.v1.SubscribeService/Subscribe',
                request_serializer=hebbs__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=hebbs__pb2.SubscribePushMessage.FromString,
                _registered_method=True)
        self.Feed = channel.unary_unary(
                '/hebbs.v1.SubscribeService/Feed',
                request_serializer=hebbs__pb2.FeedRequest.SerializeToString,
                response_deserializer=hebbs__pb2.FeedResponse.FromString,
                _registered_method=True)
        self.CloseSubscription = channel.unary_unary(
                '/hebbs.v1.SubscribeService/CloseSubscription',
                request_serializer=hebbs__pb2.CloseSubscriptionRequest.SerializeToString,
                response_deserializer=hebbs__pb2.CloseSubscriptionResponse.FromString,
                _registered_method=True)


class SubscribeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Feed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscribeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=hebbs__pb2.SubscribeRequest.FromString,
                    response_serializer=hebbs__pb2.SubscribePushMessage.SerializeToString,
            ),
            'Feed': grpc.unary_unary_rpc_method_handler(
                    servicer.Feed,
                    request_deserializer=hebbs__pb2.FeedRequest.FromString,
                    response_serializer=hebbs__pb2.FeedResponse.SerializeToString,
            ),
            'CloseSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSubscription,
                    request_deserializer=hebbs__pb2.CloseSubscriptionRequest.FromString,
                    response_serializer=hebbs__pb2.CloseSubscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hebbs.v1.SubscribeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hebbs.v1.SubscribeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SubscribeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hebbs.v1.SubscribeService/Subscribe',
            hebbs__pb2.SubscribeRequest.SerializeToString,
            hebbs__pb2.SubscribePushMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Feed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.SubscribeService/Feed',
            hebbs__pb2.FeedRequest.SerializeToString,
            hebbs__pb2.FeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.SubscribeService/CloseSubscription',
            hebbs__pb2.CloseSubscriptionRequest.SerializeToString,
            hebbs__pb2.CloseSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReflectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reflect = channel.unary_unary(
                '/hebbs.v1.ReflectService/Reflect',
                request_serializer=hebbs__pb2.ReflectRequest.SerializeToString,
                response_deserializer=hebbs__pb2.ReflectResponse.FromString,
                _registered_method=True)
        self.GetInsights = channel.unary_unary(
                '/hebbs.v1.ReflectService/GetInsights',
                request_serializer=hebbs__pb2.GetInsightsRequest.SerializeToString,
                response_deserializer=hebbs__pb2.GetInsightsResponse.FromString,
                _registered_method=True)


class ReflectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reflect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInsights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReflectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reflect': grpc.unary_unary_rpc_method_handler(
                    servicer.Reflect,
                    request_deserializer=hebbs__pb2.ReflectRequest.FromString,
                    response_serializer=hebbs__pb2.ReflectResponse.SerializeToString,
            ),
            'GetInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInsights,
                    request_deserializer=hebbs__pb2.GetInsightsRequest.FromString,
                    response_serializer=hebbs__pb2.GetInsightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hebbs.v1.ReflectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hebbs.v1.ReflectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReflectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reflect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.ReflectService/Reflect',
            hebbs__pb2.ReflectRequest.SerializeToString,
            hebbs__pb2.ReflectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.ReflectService/GetInsights',
            hebbs__pb2.GetInsightsRequest.SerializeToString,
            hebbs__pb2.GetInsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════
    Health
    ═══════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/hebbs.v1.HealthService/Check',
                request_serializer=hebbs__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hebbs__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════
    Health
    ═══════════════════════════════════════════════════════════════════════

    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=hebbs__pb2.HealthCheckRequest.FromString,
                    response_serializer=hebbs__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hebbs.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hebbs.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """═══════════════════════════════════════════════════════════════════════
    Health
    ═══════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hebbs.v1.HealthService/Check',
            hebbs__pb2.HealthCheckRequest.SerializeToString,
            hebbs__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
